on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'

jobs:
  lint:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python requirements
        run: |
          pip3 install setuptools wheel
          pip3 install black pylint
          pip3 install -r requirements.txt

      - name: Lint
        run: |
          python3 -m black --diff *.py
          python3 -m pylint *.py

  update_toolstate:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Python requirements
        run: |
          pip3 install setuptools wheel
          pip3 install -r requirements.txt

      - name: Update toolstate
        env:
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_ROLE_ID: ${{ secrets.VAULT_ROLE_ID }}
          VAULT_SECRET_ID: ${{ secrets.VAULT_SECRET_ID }}
        run: python3 update_toolstate.py

      - name: Run installer
        run: |
          python2.7 installer.py --toolchain unstable --speedrun
          python3 installer.py --toolchain unstable --speedrun --force

      # - name: Test quickstart
      #   run: |
      #     oasis init test_proj
      #     cd test_proj
      #     oasis build
      #     oasis chain -d
      #     oasis test
